import pptxgen from "pptxgenjs"

const COLORS = {
    primary: "2563EB",
    secondary: "0F172A",
    text: "334155",
    light: "F8FAFC",
    border: "E2E8F0",
    white: "FFFFFF",
    muted: "64748B",
    blueLight: "EFF6FF",
    blueSoft: "DBEAFE",
    blueAccent: "60A5FA",
}

export const generatePpt = async (data) => {
    const ppt = new pptxgen()

    ppt.layout = "LAYOUT_WIDE"
    ppt.author = "Samanvay AI"
    ppt.title = data.title
    ppt.subject = data.title
    ppt.company = "Samanvay AI"

    ppt.theme = {
        headFontFace: "Aptos",
        bodyFontFace: "Aptos"
    }

    addCover(ppt, data)

    data?.slides?.forEach((s, i) => {
        addContentSlide(
            ppt,
            s.title,
            s.points,
            i + 1,
            data.slides.length
        )
    })

    addThankYou(ppt)

    return ppt
}

const addCover = (ppt, data) => {
    const slide = ppt.addSlide()

    slide.background = {
        color: COLORS.primary
    }

    // top accent
    slide.addShape(ppt.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 13.33,
        h: 0.18,
        fill: {
            color: COLORS.blueAccent
        },
        line: {
            color: COLORS.blueAccent
        }
    })

    // decorative shapes
    slide.addShape(ppt.ShapeType.ellipse, {
        x: 10.7,
        y: -1.1,
        w: 3.8,
        h: 3.8,
        fill: {
            color: "3B82F6",
            transparency: 45
        },
        line: {
            color: "3B82F6",
            transparency: 100
        }
    })

    slide.addShape(ppt.ShapeType.ellipse, {
        x: -1.4,
        y: 5.1,
        w: 3.5,
        h: 3.5,
        fill: {
            color: "1D4ED8",
            transparency: 35
        },
        line: {
            color: "1D4ED8",
            transparency: 100
        }
    })

    slide.addShape(ppt.ShapeType.ellipse, {
        x: 1.15,
        y: 1.25,
        w: 0.12,
        h: 0.12,
        fill: {
            color: COLORS.blueAccent
        },
        line: {
            color: COLORS.blueAccent
        }
    })

    slide.addShape(ppt.ShapeType.ellipse, {
        x: 12.1,
        y: 5.4,
        w: 0.16,
        h: 0.16,
        fill: {
            color: "93C5FD"
        },
        line: {
            color: "93C5FD"
        }
    })

    slide.addText(data.title, {
        x: 0.7,
        y: 1.7,
        w: 12,
        h: 0.8,
        align: "center",
        color: COLORS.white,
        bold: true,
        fontSize: 28,
        fit: "shrink"
    })

    slide.addText(data.subtitle, {
        x: 1,
        y: 2.8,
        w: 11.5,
        h: 0.5,
        align: "center",
        color: "DBEAFE",
        fontSize: 15,
        fit: "shrink"
    })

    // accent line
    slide.addShape(ppt.ShapeType.line, {
        x: 5.6,
        y: 3.55,
        w: 2.1,
        h: 0,
        line: {
            color: "93C5FD",
            width: 2
        }
    })

    slide.addText("Generated By Samanvay AI", {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.2,
        align: "center",
        color: "BFDBFE",
        fontSize: 10
    })
}

function addContentSlide(
    ppt,
    title,
    points,
    page,
    total
) {
    const slide = ppt.addSlide()

    slide.background = {
        color: COLORS.white
    }

    // left accent
    slide.addShape(ppt.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 0.1,
        h: 7.5,
        fill: {
            color: COLORS.primary
        },
        line: {
            color: COLORS.primary
        }
    })

    // top right decoration
    slide.addShape(ppt.ShapeType.ellipse, {
        x: 12.2,
        y: -0.55,
        w: 1.7,
        h: 1.7,
        fill: {
            color: COLORS.blueSoft,
            transparency: 35
        },
        line: {
            color: COLORS.blueSoft,
            transparency: 100
        }
    })

    slide.addShape(ppt.ShapeType.ellipse, {
        x: 11.85,
        y: 0.25,
        w: 0.12,
        h: 0.12,
        fill: {
            color: COLORS.primary
        },
        line: {
            color: COLORS.primary
        }
    })

    slide.addText(title, {
        x: 0.6,
        y: 0.35,
        w: 10.8,
        h: 0.4,
        fontSize: 24,
        bold: true,
        color: COLORS.primary,
        fit: "shrink"
    })

    slide.addShape(ppt.ShapeType.line, {
        x: 0.6,
        y: 0.85,
        w: 12,
        h: 0,
        line: {
            color: COLORS.border,
            width: 1.2
        }
    })

    const visiblePoints = Array.isArray(points)
        ? points.slice(0, 6)
        : []

    visiblePoints.forEach((point, i) => {
        const y = 1.2 + i * 0.75

        // content card
        slide.addShape(ppt.ShapeType.roundRect, {
            x: 0.7,
            y,
            w: 12,
            h: 0.58,
            rectRadius: 0.08,
            fill: {
                color: i % 2
                    ? COLORS.light
                    : COLORS.blueLight
            },
            line: {
                color: COLORS.border,
                width: 0.7
            }
        })

        // bullet
        slide.addShape(ppt.ShapeType.ellipse, {
            x: 0.92,
            y: y + 0.18,
            w: 0.12,
            h: 0.12,
            fill: {
                color: COLORS.primary
            },
            line: {
                color: COLORS.primary
            }
        })

        slide.addText(point, {
            x: 1.2,
            y: y + 0.08,
            w: 11,
            h: 0.35,
            fontSize: 15,
            color: COLORS.text,
            fit: "shrink",
            margin: 0
        })
    })

    // progress bar
    const progress = total > 0
        ? Math.min(page / total, 1)
        : 0

    slide.addShape(ppt.ShapeType.rect, {
        x: 9.7,
        y: 6.9,
        w: 2.1,
        h: 0.055,
        fill: {
            color: COLORS.border
        },
        line: {
            color: COLORS.border,
            transparency: 100
        }
    })

    slide.addShape(ppt.ShapeType.rect, {
        x: 9.7,
        y: 6.9,
        w: 2.1 * progress,
        h: 0.055,
        fill: {
            color: COLORS.primary
        },
        line: {
            color: COLORS.primary,
            transparency: 100
        }
    })

    slide.addText("Samanvay AI", {
        x: 0.6,
        y: 6.85,
        w: 2,
        h: 0.2,
        fontSize: 10,
        bold: true,
        color: COLORS.muted,
        margin: 0
    })

    slide.addText(`${page}/${total}`, {
        x: 12.1,
        y: 6.85,
        w: 0.65,
        h: 0.2,
        align: "right",
        fontSize: 10,
        color: COLORS.muted,
        margin: 0
    })
}

const addThankYou = (ppt) => {
    const slide = ppt.addSlide()

    slide.background = {
        color: COLORS.secondary
    }

    // top accent
    slide.addShape(ppt.ShapeType.rect, {
        x: 0,
        y: 0,
        w: 13.33,
        h: 0.15,
        fill: {
            color: COLORS.primary
        },
        line: {
            color: COLORS.primary
        }
    })

    // decorative shapes
    slide.addShape(ppt.ShapeType.ellipse, {
        x: 10.7,
        y: -1,
        w: 3.7,
        h: 3.7,
        fill: {
            color: COLORS.primary,
            transparency: 45
        },
        line: {
            color: COLORS.primary,
            transparency: 100
        }
    })

    slide.addShape(ppt.ShapeType.ellipse, {
        x: -1.3,
        y: 5.1,
        w: 3.4,
        h: 3.4,
        fill: {
            color: "1E40AF",
            transparency: 40
        },
        line: {
            color: "1E40AF",
            transparency: 100
        }
    })

    slide.addText("Thank You", {
        x: 0,
        y: 2.2,
        w: 13.33,
        h: 0.8,
        align: "center",
        color: COLORS.white,
        fontSize: 34,
        bold: true
    })

    slide.addShape(ppt.ShapeType.line, {
        x: 5.6,
        y: 3.3,
        w: 2.1,
        h: 0,
        line: {
            color: COLORS.blueAccent,
            width: 2
        }
    })

    slide.addText("Generated By Samanvay AI", {
        x: 0,
        y: 6.9,
        w: 13.33,
        h: 0.2,
        align: "center",
        color: "94A3B8",
        fontSize: 10
    })
}